export const SET_AUTH = 'SET_AUTH';
export const REMOVE_AUTH = 'REMOVE_AUTH';
// SIGN UP
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// SIGN IN
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';

// SIGN OUT
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';

// RESET PASSWORD
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_ERROR = 'RESET_ERROR';

// CHANGE EMAIL
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const EMAIL_ERROR = 'EMAIL_ERROR';
